-- =========================
-- 1) Esquemas
-- =========================
create schema if not exists public;

-- =========================
-- 2) Tipos ENUM (public)
-- =========================
do $$
begin
  if not exists (select 1 from pg_type t join pg_namespace n on n.oid=t.typnamespace where t.typname='user_role' and n.nspname='public') then
    create type public.user_role as enum ('estudiante', 'repartidor', 'cafeteria', 'admin');
  end if;

  if not exists (select 1 from pg_type t join pg_namespace n on n.oid=t.typnamespace where t.typname='rider_approval_status' and n.nspname='public') then
    create type public.rider_approval_status as enum ('pendiente', 'aprobado', 'rechazado');
  end if;

  if not exists (select 1 from pg_type t join pg_namespace n on n.oid=t.typnamespace where t.typname='location_status' and n.nspname='public') then
    create type public.location_status as enum ('pendiente', 'aprobado', 'rechazado');
  end if;

  if not exists (select 1 from pg_type t join pg_namespace n on n.oid=t.typnamespace where t.typname='order_status' and n.nspname='public') then
    create type public.order_status as enum ('pendiente', 'preparando', 'listo_para_entrega', 'en_camino', 'entregado', 'cancelado');
  end if;

  if not exists (select 1 from pg_type t join pg_namespace n on n.oid=t.typnamespace where t.typname='payment_status' and n.nspname='public') then
    create type public.payment_status as enum ('pendiente', 'verificado', 'rechazado');
  end if;
end $$;



-- =========================
-- 3) Tablas public
-- =========================
create table if not exists public.profiles (
  id uuid primary key references auth.users(id),
  role public.user_role not null default 'estudiante',
  full_name text,
  phone text,
  avatar_url text,
  cedula text,
  driver_license_url text,
  account_type text,
  bank_name text,
  account_number text,
  rider_approval public.rider_approval_status default 'pendiente',
  is_available_for_delivery boolean default false,
  created_at timestamptz not null default now()
);

create table if not exists public.allowed_email_domains (
  id integer generated by default as identity primary key,
  domain text not null unique
);

create table if not exists public.banks_catalog (
  id integer generated by default as identity primary key,
  name text not null unique
);

create table if not exists public.cafeterias (
  id integer generated by default as identity primary key,
  owner_id uuid not null references public.profiles(id),
  name text not null,
  description text,
  physical_location text,
  is_active boolean not null default false,
  logo_url text,
  created_at timestamptz not null default now()
);

create table if not exists public.product_categories (
  id integer generated by default as identity primary key,
  cafeteria_id integer not null references public.cafeterias(id),
  name text not null,
  sort_order integer default 0
);

create table if not exists public.products (
  id integer generated by default as identity primary key,
  cafeteria_id integer not null references public.cafeterias(id),
  category_id integer references public.product_categories(id),
  name text not null,
  description text,
  price numeric not null check (price >= 0.00),
  image_url text,
  is_available boolean not null default true,
  created_at timestamptz not null default now(),
  is_promo boolean not null default false
);

create table if not exists public.delivery_locations (
  id integer generated by default as identity primary key,
  name text not null,
  description text,
  status public.location_status not null default 'pendiente',
  suggested_by uuid references public.profiles(id),
  approved_by uuid references public.profiles(id),
  created_at timestamptz not null default now()
);

create table if not exists public.orders (
  id integer generated by default as identity primary key,
  student_id uuid not null references public.profiles(id),
  cafeteria_id integer not null references public.cafeterias(id),
  delivery_rider_id uuid references public.profiles(id),
  delivery_location_id integer not null references public.delivery_locations(id),
  status public.order_status not null default 'pendiente',
  total_amount numeric not null check (total_amount >= 0),
  delivery_fee numeric not null default 1.00 check (delivery_fee >= 0),
  payment_proof_path text,
  payment_status public.payment_status not null default 'pendiente',
  verified_by_cafeteria boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.order_items (
  id integer generated by default as identity primary key,
  order_id integer not null references public.orders(id),
  product_id integer not null references public.products(id),
  quantity integer not null check (quantity > 0),
  unit_price numeric not null check (unit_price >= 0)
);

create table if not exists public.delivery_otps (
  order_id integer primary key references public.orders(id),
  otp_code text not null,
  attempts integer not null default 0 check (attempts <= 5),
  created_at timestamptz not null default now()
);

create table if not exists public.reviews (
  id integer generated by default as identity primary key,
  order_id integer not null unique references public.orders(id),
  student_id uuid not null references public.profiles(id),
  cafeteria_id integer not null references public.cafeterias(id),
  rating integer not null check (rating >= 1 and rating <= 5),
  comment text,
  created_at timestamptz not null default now()
);

create table if not exists public.rider_payments (
  id integer generated by default as identity primary key,
  rider_id uuid not null references public.profiles(id),
  cafeteria_id integer not null references public.cafeterias(id),
  order_id integer references public.orders(id),
  amount numeric not null check (amount >= 0),
  week_start date not null,
  week_end date not null,
  paid boolean not null default false,
  paid_at timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists public.terms_acceptance (
  id integer generated by default as identity primary key,
  user_id uuid not null references public.profiles(id),
  accepted_terms_version text not null,
  accepted_at timestamptz not null default now()
);

create table if not exists public.cafeteria_bank_accounts (
  id integer generated by default as identity primary key,
  cafeteria_id integer not null references public.cafeterias(id),
  bank_name text not null,
  account_number text not null,
  account_type text not null,
  account_holder_name text,
  is_primary boolean not null default false
);

-- =========================
-- 4) RLS habilitado (tablas public)
-- =========================
alter table public.profiles enable row level security;
alter table public.allowed_email_domains enable row level security;
alter table public.banks_catalog enable row level security;
alter table public.cafeterias enable row level security;
alter table public.cafeteria_bank_accounts enable row level security;
alter table public.product_categories enable row level security;
alter table public.products enable row level security;
alter table public.delivery_locations enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;
alter table public.delivery_otps enable row level security;
alter table public.reviews enable row level security;
alter table public.rider_payments enable row level security;
alter table public.terms_acceptance enable row level security;
